version: '3.8'

services:
  app:
    build: .
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  nginx:
    image: nginx:latest
    ports:
      - "3007:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app